Possedin
RhysB/Project-Poseidon pull request #61
Opened 2023-03-11 20:19 UTC by Strultz

* [Fix bow sound playing twice](https://github.com/RhysB/Project-Poseidon/commit/9ff09ee3cee0d7140f0a0d013da39d0d3f0679b4)
* [Fast packets](https://github.com/RhysB/Project-Poseidon/commit/3609ce2cced8cb00af58048dfbd0c3f3f93e3ea7)
* [Option to fix the drowning pushdown](https://github.com/RhysB/Project-Poseidon/commit/f72dec19577b4263f5fde468befc68e41cb9bfd7)

2023-03-11 21:02 UTC, CodeKid0 commented
so true

2023-03-11 21:21 UTC, CodeKid0 requested changes
Please fix formatting (too much spaces/tabs [don't use tabs])

2023-03-11 22:58 UTC, CodeKid0 requested changes

2023-03-11 22:58 UTC, CodeKid0 commented on src/net/minecraft/server/NetServerHandler.java
> +        String leaveMessage = PoseidonConfig.getInstance().getConfigString("message.player.leave").replace("%player%", this.player.name);
Could you do it the same as I did in my commits? Otherwise, everything's good!

2023-03-11 22:58 UTC, CodeKid0 commented
btw I didn't request to remove all tabs but I'm grateful you did it.

2023-03-11 23:12 UTC, CodeKid0 commented
FIX THE TABS. FIX THE MOTHERFUCKIN TABS. THE VOICES TELL ME YOU SHOULD FIX THE TABS

2023-03-11 23:15 UTC, CodeKid0 approved these changes
*merge*

2023-03-12 02:24 UTC, RhysB commented
lgtm

2023-03-12 02:24 UTC, merged